--- #YAML:1.0
name:                Domain-Register-DomainShare
version:             1.02
abstract:            ~
license:             ~
author:              
    - Dot TK Limited <partners@dot.tk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    REST::Client:                  164
    URI::Escape:                   3.29
    XML::Simple:                   2.18
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
